name: Build Tauri

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux build
          - os: ubuntu-22.04
            target: ""

          # Windows build
          - os: windows-latest
            target: ""

          # macOS (Apple Silicon - ARM64)
          - os: macos-latest
            target: "aarch64-apple-darwin"

          # macOS (Intel - x86_64)
          - os: macos-latest
            target: "x86_64-apple-darwin"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt

      - name: Install dependencies
        run: bun install

      - name: Install dependencies (ubuntu only)
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Build Tauri App
        if: matrix.target == ''
        run: bun tauri build

      - name: Build Tauri App with target
        if: matrix.target != ''
        run: bun tauri build --target ${{ matrix.target }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}-${{ matrix.target || 'default' }}
          path: |
            src-tauri/target/release/bundle/
