# name: Build Tauri

# on:
#   # push:
#   #   branches:
#   #     - main
#   # pull_request:

# jobs:
#   build:
#     runs-on: ${{ matrix.os }}
#     strategy:
#       matrix:
#         os: [ubuntu-latest]

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Bun
#         uses: oven-sh/setup-bun@v1

#       - name: Install Rust
#         uses: actions-rs/toolchain@v1
#         with:
#           toolchain: stable
#           components: rustfmt

#       - name: Install dependencies
#         run: |
#           bun install
#           cargo install tauri-cli

#       - name: Build Tauri App
#         run: |
#           mkdir out
#           bun tauri build
